<img src="Figurer/NTNU_Logo.png" align="left">
<br clear="all">

<br/><br/>



# While-løkker (og Matriser)


* Emne INGA1002 - Programmering, numerikk og sikkerhet
* Avsluttende tema i Programmering
* Underviser: Kai Erik Hoff


<br/><br/>

# Tema:
* While-løkker
* Løkker med "logg"
* Kort om matriser

# While-løkker som konsept
<img src="Figurer/While_flowchart.png" width="70%" align="left">

# Å Skrive en while-løkke

* Generelt format fo en while-løkke i python
```python
while betingelse: # hvis True så...
    kodelinje1 # Én linje som kjøres i løkken
    kodelinje2 # Enda en linje som kjøres i løkken
kodelinje3 # Utføres etter at løkken er avsluttet
```

* Hvis betingelsen er `True` vil kodelinje 1 og 2 bli uført om og om igjen helt til betingelsen blir `False`
    * Kun kode med innrykk hører til while-løkka (altså ikke kodelinje 3)
    * Kodelinje 3 og videre kjøres etter at betingelsen er satt til false.

## While og For
* Hvordan de ulike løkkene teller opp til 5:

In [2]:
%%html
<iframe width="1000" height="500" frameborder="0" src="https://pythontutor.com/iframe-embed.html#code=%23%20While-l%C3%B8kke%20teller%20opp%20til%205%0Ax%20%3D%200%0Awhile%20x%20%3C%205%3A%0A%20%20%20%20print%28x%29%0A%20%20%20%20x%20%2B%3D%201%0A%20%20%20%20%0A%23%20For-l%C3%B8kke%20teller%20opp%20til%205%0Afor%20x%20in%20range%285%29%3A%0A%20%20%20%20print%28x%29&codeDivHeight=400&codeDivWidth=350&cumulative=false&curInstr=0&heapPrimitives=nevernest&origin=opt-frontend.js&py=311&rawInputLstJSON=%5B%5D&textReferences=false"> </iframe>

## Eksempel 1:
Vi har variablen $x=1$. Den skal ganges med to om og om igjen, til den er større enn $100$. Vi vil finne antallet ganginger vi trenger for å få dette til. Bruk en while-løkke til å gjøre dette.

In [2]:
%%html
<iframe width="1000" height="500" frameborder="0" src="https://pythontutor.com/iframe-embed.html#code=x%20%3D%201%0Ateller%20%3D%200%0A%0Awhile%20x%20%3C%3D%20100%3A%0A%20%20%20%20x%20*%3D%202%0A%20%20%20%20teller%20%2B%3D%201%0A%0Aprint%28f'Resulterende%20x%3A%20%7Bx%7D'%29%0Aprint%28f'Antall%20ganginger%3A%20%7Bteller%7D'%29&codeDivHeight=400&codeDivWidth=350&cumulative=false&curInstr=0&heapPrimitives=nevernest&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false"> </iframe>

## Eksempel 2: søk i liste
Skriv en funksjon som søker gjennom en liste, og finner posisjonen til *den første* instansen av en tallverdi.

## Eksempel 3: blind ligningsløsning

Bruk while-løkker til å løse ligningen $x^3 + 5\cdot x  = 10$ ved hjelp av tilfeldig gjetting.

In [ ]:
import random as rnd

### Unngå evige løkker!

* Hvis man ikke passer på, kan man definere en betingelse for while-løkken som _aldri_ blir `False`.
* Da vil løkken fortsette å repetere evig, og programmet "henger seg opp".
* Pass på at det _alltid_ finnes en realiserbar måte for programmet å komme seg ut av løkken.

# Matriser

* Matriser er 2-dimensjonale arrays med både *rader* og *kolonner*

* En matrise kan defineres som følger:
$$ A = \begin{bmatrix}
    a_{00} & a_{01} & a_{02} \\
    a_{10} & a_{11} & a_{12} \\
    a_{20} & a_{21} & a_{22}
\end{bmatrix} $$
    hvor $a_{ij}$ refererer til verdien på rad $i$ og kolonne $j$. 
    
    
* I Python blir dette:

In [ ]:
import numpy as np
A = np.array([['a_00', 'a_01', 'a_02'],
              ['a_10', 'a_11', 'a_12'],
              ['a_20', 'a_21', 'a_22']])

## Konkret eksempel på matrise med verdier

$$ B = \begin{bmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    7 & 8 & 9
\end{bmatrix} $$

* $a_{01} = 2$. 
    * Rad-indeks $0$ (eller rad nummer fra toppen).
    * Kolonne-indeks 1, (eller andre kolonne fra venstre). 

In [3]:
import numpy as np
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Indeksering:
* Bruker komma for å separere koordinater: `A[rad, kolonne]`

In [6]:
B[0,1]

2

# Å finne dimensjonene til en matrise

* Antall rader og kolonner er tilgjengelig med funksjonen `numpy.shape()`.

In [11]:
C = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [0, 10, 11, 10]])

rows, cols = np.shape(C)
print(f"{rows} rader og {cols} kolonner.")

3 rader og 4 kolonner.


# Regneoperasjoner med matriser

* På samme måte som vanlige numpy-arrays kan vi utføre elementvise regneoperasjoner på matriser med vanlige matematiske operatorer

* Eksempel:

$$b_{ij} = 2\cdot a_{ij}^2 - 3$$

In [12]:
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
B = 2*A**2-3
B

array([[ -1,   5,  15],
       [ 29,  47,  69],
       [ 95, 125, 159]])

# Matriser i funksjoner

* Vi kan også bruke matriser som input til matematiske funksjoner.
$$f(x) = 2\cdot x^2 - 3$$

In [13]:
def f(x):
    y = 2*x**2-3
    return y
f(A)

array([[ -1,   5,  15],
       [ 29,  47,  69],
       [ 95, 125, 159]])

# "Manuell" elementvis prosessering

* For å gjøre en handling med hvert element i en matrise (f.eks. if-setning) er det fordelaktig å bruke *nøstede for-løkker*

$$b_{ij} = \begin{cases} 2\cdot a_{ij}^2 - 3, \ \ \ j>i \\ 0, \ \ \ \text{otherwise} \end{cases}$$

* NB! Her må vi lage en "tom" matrise for $B$ med riktige dimensjoner først.

In [16]:
rows, cols = np.shape(A)
B = np.zeros([rows, cols])
for j in range(rows):
    for i in range(cols):
        if j > i:
            B[i][j] = 2*A[i][j]**2 - 3
        else: 
            B[i][j] = 0
B

array([[ 0.,  5., 15.],
       [ 0.,  0., 69.],
       [ 0.,  0.,  0.]])

# Spørsmål?